### ISSUE TITLE
Custom CIDR Range

### ISSUE THREAD

**Issue by galebm1004** [NetApp/terraform-provider-netapp-gcp#36]
Creating a custom CIDR Range is an available option for configuring a netapp volume in GCP however it does not appear to be a supported argument in the terraform. https://registry.terraform.io/providers/NetApp/netapp-gcp/latest/docs/resources/volume.

**Comment by okrause** [comment]
I am not sure if I understand correctly.
My assumption is, that you are about to create your first volume and did not do the on-boarding of the CVS service yet. The UI is a bit misleading here, since the on-boarding workflow is hidden behind the "create volume" workflow. here is a description of the workflow: https://cloud.google.com/solutions/partners/netapp-cloud-volumes/quickstart?hl=en_US

On-boarding and volume creation are in reality two separate things. This TF provider manages volume management. The on-boarding process is done through Google means and can be automated through the "Google" TF provider.
If you don't have to automate the full on-boarding process, I recommend doing the on-boarding manually and than do Volume/ActiveDirectory/Snapshot management through this TF provider.

**Comment by okrause** [comment]
You might want to have a look at #37

**Comment by galebm1004** [comment]
Thank you, this was helpful!
